services:
  - type: web
    name: signsync-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 flask_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
